### ISSUE TITLE
Create reference architecture for handling binary payloads with IoT Core

### ISSUE THREAD

**Issue by timmattison** [aws-samples/iot-reference-architectures#4]
Binary payload handling is a request that comes up often in my discussions. Having a simple reference architecture in this repo would benefit a lot of customers.

If you're interested in seeing this built please +1 this issue.

**Comment by bridress** [comment]
This would be very beneficial as we are seeing MQTT deployments that are moving to binary payloads in the industrial space.  I think this is very beneficial for customers to have this capability to have that native support.

**Comment by timmattison** [comment]
Created an Amazon Ion example and a CBOR example for this.
